### PR TITLE
adding kotlin flows and details movie call

### PR DESCRIPTION
**Pull request by inaki92**
I moved the logic for getting the response from viewmodel to the repository layer, using koltin flow and state flow for the movie details.

TODO added to make the details movie logic

### CODE REVIEW

**Review by TonyStarkWiz — APPROVED** [review]

**Review by BelliJoseph — APPROVED** [review]
Looks Great!

**Review by hcdisat — APPROVED** [review]
LGTM

**Review by Abra-Sena — COMMENTED** [review]
Good!

**Review by 7yes — COMMENTED** [review]
LGTM

**Pull request merged**
