### PR TITLE
DI using hilt

### PR DESCRIPTION
**Pull request by inaki92**
hilt dependency injection

### CODE REVIEW

**Review by aaronb305 — APPROVED** [review]
LGTM

**Review by BelliJoseph — APPROVED** [review]
This looks Awesome!

**Review by yuminhao8888 — APPROVED** [review]

**Review by Abra-Sena — APPROVED** [review]
Good job with the fix!

**Review by OlegAndroidDev — APPROVED** [review]
LGTM again

**Review by tatanka1997 — APPROVED** [review]

**Review by TonyStarkWiz — APPROVED** [review]
Excellent

**Review by hcdisat — APPROVED** [review]
LGTM

**Review by BurnHealVendor — APPROVED** [review]
LGTM

**Comment by 7yes** [comment]
K

**Pull request merged**
