### PR TITLE
view model factory implemented no DI

### PR DESCRIPTION
**Pull request by inaki92**
DI with HILT

### CODE REVIEW

**Review by aaronb305 — APPROVED** [review]
LGTM

**Review by hcdisat — APPROVED** [review]
LGTM

**Review by TylerdEntremont — APPROVED** [review]
LGTM

**Review by BurnHealVendor — APPROVED** [review]
LGTM

**Review by OlegAndroidDev — APPROVED** [review]
LGTM

**Review by tatanka1997 — APPROVED** [review]

**Review by afgar88 — COMMENTED** [review]
Nice job

**Review by tatanka1997 — APPROVED** [review]
LGTM

**Comment by yuminhao8888** [comment]
good job

**Review by TonyStarkWiz — APPROVED** [review]
Excellent

**Comment by 7yes** [comment]
LGTM

**Comment by Abra-Sena** [comment]
LGTM

**Review by Abra-Sena — COMMENTED** [review]
LGTM

**Review by afgar88 — COMMENTED** [review]
thake care with the commits :)

**Pull request merged**
